---
- name: Install WAF
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: yes
  roles:
    - role: waf
      environment:
        http_proxy: "{{PROXY}}"
        https_proxy: "{{PROXY}}"